# Generated by Django 3.0.7 on 2020-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('course', models.CharField(choices=[('CC', 'Ciência da Computação'), ('FS', 'Física'), ('EN', 'Enfermagem'), ('EC', 'Engenharia Civil'), ('AR', 'Arquitetura'), ('QU', 'Química')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
