# Generated by Django 3.0.7 on 2020-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studants', '0004_auto_20200826_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
