# Generated by Django 3.0.7 on 2020-08-26 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studants', '0006_auto_20200826_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='studant',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
