# Generated by Django 3.0.7 on 2020-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studants', '0002_auto_20200826_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studant',
            name='birthday',
        ),
        migrations.AddField(
            model_name='studant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
