# Generated by Django 3.0.7 on 2020-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studants', '0009_auto_20200826_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studant',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
