# Generated by Django 3.1 on 2020-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studants', '0010_auto_20200826_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studant',
            name='address',
        ),
        migrations.AddField(
            model_name='studant',
            name='city',
            field=models.CharField(default='Viçosa do Ceará', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='birth_date',
            field=models.DateField(verbose_name='Data  de Nasimento'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='course',
            field=models.CharField(choices=[('Ciência da Computação', 'Ciência da Computação'), ('Física', 'Física'), ('Enfermagem', 'Enfermagem'), ('Engenharia Civil', 'Engenharia Civil'), ('Arquitetura', 'Arquitetura'), ('Química', 'Química')], max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='studant',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
